### PR TITLE
 __MACOSX: Remove

### LINKED ISSUE #1: Remove _MACOSX directory
https://github.com/kubeflow/marketing-materials/tree/master/logos/__MACOSX is useless, IMO. We could delete it from the repository.

### PR DESCRIPTION
**Pull request by gaocegege**
- Remove __MACOSX Close #1
- Add README

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/marketing-materials/2)

### CODE REVIEW

**Comment by gaocegege** [comment]
/assign @aronchick 

We do not add owners for the repository thus maybe we need to merge it manually.

**Comment by jlewi** [comment]
Is this PR still relevant?

**Comment by gaocegege** [comment]
@jlewi I still think we should remove the __MACOSX since it is useless.

**Pull request merged**
